packages:
  - package
  - examples/*

catalog:
  '@hono/zod-openapi': ^1.1.4
  hono: ^4.10.3
  tsx: ^4.20.6
  typescript: ^5.9.3

catalogs:
  examples:
    '@hono/node-server': ^1.19.5
    '@scalar/hono-api-reference': ^0.9.22
    '@types/node': ^24.9.1
    wrangler: ^4.45.0
  package:
    '@vitest/coverage-v8': ^4.0.3
    '@vitest/ui': ^4.0.3
    tsup: ^8.5.0
    typedoc: ^0.28.14
    vitest: ^4.0.3
    zod: ^4.1.12
