packages:
  - package
  - 'examples/*'

catalog:
  '@hono/zod-openapi': ^1.1.3
  hono: ^4.9.9
  tsx: ^4.20.6
  typescript: ^5.9.3

catalogs:
  examples:
    '@hono/node-server': ^1.19.5
    '@scalar/hono-api-reference': ^0.9.19
    '@types/node': ^20.11.17
    wrangler: ^4.4.0
  package:
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    tsup: ^8.5.0
    typedoc: ^0.28.13
    vitest: ^3.2.4
